#!/bin/bash

# Live Version -- An insurance system for your precious work.
#
# Copyright 2014 Anupam Arohi. All rights reserved.
#
# Original blog post presenting this system is found at: 
# http://lv.anupam-arohi.com/
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met: 
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY ANUPAM AROHI ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL ANUPAM AROHI OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are
# those of the authors and should not be interpreted as representing official
# policies, either expressed or implied, of Anupam Arohi
#

# Syntax check
if [ -z "$2" ]; then
	echo "Usage: $0 /full/source/path /full/destination/path [/log/file] [your@email.address]"
	echo "Note: If you give email address, please also give log file."
	echo
	exit
fi

# Variables
SRC=`echo "${1%/}"`                              # delete trailing slashes for rsync
DES=`echo "${2%/}"` 
LOG="$3"
EMAIL="$4"
lvDIR="$DES/.lv"

function email_log() { 									  
	if [ ! -z "$LOG" ] && [ ! -z "$EMAIL" ]; then
			mailx -s "Live Version | `hostname` | $SRC --> $DES" $EMAIL < "$LOG"
	fi
}

function on_error() {
	email_log
	exit
}

trap on_error ERR

# Logging
if [ ! -z "$LOG" ]; then
	exec > >(tee "$LOG")									 # use tee -a to append to log file
	exec 2>&1
fi

echo 
echo "-- Live Version started at   : `date` --"
echo 
echo "$SRC --> $DES"
echo 

# Setup
if [ ! -d "$lvDIR" ]; then

	echo "Setting up Live Repository"

	mkdir -p "$lvDIR"
	cd "$DES"

	echo ".lv/" > .gitignore								# we don't want to track maintenance files

	cd "$lvDIR"

   # Exclude these patterns while copying using rsync
	cp $HOME/.LiveVersion/exclude_rsync .
	cp $HOME/.LiveVersion/exclude_diff .

	cd .. #  lvDIR -> $DES

	git init
	git add . -Av
	git commit -m "Live Repository initialized!"

	git log  -1 | head -1 | cut -f2 -d' ' > "$lvDIR"/lastSHA 

	echo "Live Repository is ready in $DES."
	echo
# Setup - X -
else
	# Check if it makes sense to execute further
	# exclude_diff is like exclude_rsync but made for diff command
	# even when one of excluded files is updated, rsync would execute
	# We don't want live version to execute in this case, so we use diff to check the state of files.

	if [ ! -f $lvDIR/exclude_diff ]; then
		if [ -f $HOME/.LiveVersion/exclude_diff ]; then
			cp $HOME/.LiveVersion/exclude_diff $lvDIR/
		else
			echo "File exclude_diff is missing, download live-version again and run setup"
			exit
		fi
	fi
	DFNAME=`echo "$SRC" | rev | cut -d'/' -f1 | rev` # destination folder name without the path
	DIFF=`diff -rwq --exclude-from $lvDIR/exclude_diff "$SRC" "$DES/$DFNAME" | head -1`

	if [ -z "$DIFF" ]; then
		echo "$SRC unchanged since last sync, terminating."
		echo
		echo "-- Live Version terminated at: `date` --"
		exit
	fi
fi

lastSHA=`cat "$lvDIR"/lastSHA` 							  # It will act as recovery point in case you checked out some other sha

cd "$DES"

currentSHA=`git log  -1 | head -1 | cut -f2 -d' '`
if [ "$currentSHA" != "$lastSHA" ]; then
	git checkout $lastSHA
fi


#  Sync
rsync -aruvh --delete --exclude-from "$lvDIR"/exclude_rsync "$SRC" "$DES" # Add more excludes as per your needs to exclude_rsync
#  Sync - X - 

git add . -Av 
git commit -m "After Sync. [`date`]" || true 
git log  -1 | head -1 | cut -f2 -d' ' > "$lvDIR"/lastSHA


echo
echo "-- Live Version ended at     : `date` --"


# in case you're watching folders that change seldom and you want to be
# informed whenever they do, add an empty file named "always_email_log" in .lv folder
# of destination directory.
if [ ! -z "$EMAIL" ] && [ ! -z "$LOG" ] && [ -f $lvDIR/always_email_log ]; then
	nothingChanged=`grep "nothing to commit" $LOG`
	if [ -z "$nothingChanged" ]; then
		email_log
	fi
fi

